var funtionsVanilla = require("./funtions");
console.log(funtionsVanilla.calArea("CirCuLo", 23, 10, 45, 34));
console.log(funtionsVanilla.calArea("cUADRAdo", 23, 10, 45, 34));
console.log(funtionsVanilla.calArea("TriangUlO", 23, 10, 45, 34));
console.log(funtionsVanilla.calArea("RectaNGulo", 23, 10, 45, 34));
console.log(funtionsVanilla.numRamdon(100, 100, 200));
console.log(funtionsVanilla.esPrimo(12));
console.log(funtionsVanilla.esPrimo(7));
console.log(funtionsVanilla.esPrimo(3));
console.log(funtionsVanilla.esPrimo(16));
