var funtionsVanilla = require("./funtions");
console.log(funtionsVanilla.calArea("CirCuLo", 23, 10, 45, 34));
console.log(funtionsVanilla.calArea("cUADRAdo", 23, 10, 45, 34));
console.log(funtionsVanilla.calArea("TriangUlO", 23, 10, 45, 34));
console.log(funtionsVanilla.calArea("RectaNGulo", 23, 10, 45, 34));
console.log(funtionsVanilla.numRamdon(4, 100, 200));
console.log(funtionsVanilla.esPrimo(12));
console.log(funtionsVanilla.esPrimo(7));
console.log(funtionsVanilla.esPrimo(3));
console.log(funtionsVanilla.esPrimo(16));
console.log(funtionsVanilla.esFactorial(5));
console.log(funtionsVanilla.esFactorial(6));
console.log(funtionsVanilla.esFactorial(12));
console.log(funtionsVanilla.esBinario(6767));
console.log(funtionsVanilla.numCifras(1296716237198212));
console.log(funtionsVanilla.cambioMoneda(354, "libRAs"));
console.log(funtionsVanilla.cambioMoneda(2634, "YeN"));
console.log(funtionsVanilla.cambioMoneda(12234, "DolAr"));
console.log(funtionsVanilla.arraNum(7));
console.log(funtionsVanilla.arraNum(9));
console.log(funtionsVanilla.arraNum(2));
console.log(funtionsVanilla.primoAleatorio(2));
console.log(funtionsVanilla.primoAleatorio(4));
